- name: Remove docker image
  docker_image:
    name: my_first_webpage
    tag: local
    force_absent: true
    state: absent

- name: Build docker image
  docker_image:
    name: my_first_webpage
    tag: local
    build:
      path: /vagrant/docker
      pull: false
      http_timeout: 120
    source: build

- name: Create tmp if it does not exist
  file:
    path: /vagrant/dev/tmp
    state: directory
    mode: '0755'
    owner: vagrant
    group: vagrant

- name: Archive docker image
  docker_image:
    name: your_first_ml_model
    tag: local
    archive_path: /vagrant/dev/tmp/my_first_webpage.tar
    source: local